# Generated by Django 4.2.16 on 2024-12-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_taskassignment_api_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='tasks_completed',
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='api_response',
            field=models.JSONField(blank=True, null=True, verbose_name='API Response'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='media_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Media ID'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='task_screenshots/'),
        ),
    ]
