# Generated by Django 4.2.16 on 2024-11-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
