# Generated by Django 4.2.16 on 2024-12-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_referral_tasks_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='tasks_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
