# Generated by Django 4.2.16 on 2024-11-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_redemptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='task_screenshots/'),
        ),
    ]
