# Generated by Django 4.2.16 on 2024-12-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_customuser_bonus_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassignment',
            name='media_id',
        ),
    ]
