# Generated by Django 4.2.16 on 2024-12-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_taskassignment_media_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='media_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Media ID'),
        ),
    ]
