# Generated by Django 4.2.16 on 2024-11-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_media_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='media_id',
        ),
        migrations.AddField(
            model_name='task',
            name='edia_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Media ID'),
        ),
    ]
