# Generated by Django 4.2.16 on 2024-12-19 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_taskassignment_media_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referrallink',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='referrallink',
            name='referral_link',
        ),
        migrations.AddField(
            model_name='referrallink',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referrallink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
