# Generated by Django 4.2.16 on 2024-12-19 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_referrallink_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCompletionBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks_completed', models.IntegerField()),
                ('points_awarded', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_bonus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
