# Generated by Django 4.2.16 on 2024-12-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_taskcompletionbonus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskCompletionBonus',
        ),
    ]
