# Generated by Django 4.2.16 on 2024-11-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_rename_edia_id_task_media_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='api_response',
            field=models.JSONField(blank=True, null=True, verbose_name='API Response'),
        ),
    ]
