# Generated by Django 4.2.16 on 2024-11-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_taskassignment_api_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='media_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Media ID'),
        ),
    ]
