# Generated by Django 4.2.16 on 2024-12-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_referral_bonus_credited'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks_required', models.PositiveIntegerField(help_text='Number of tasks to complete for this milestone.')),
                ('points', models.PositiveIntegerField(help_text='Points to award upon reaching this milestone.')),
            ],
            options={
                'verbose_name': 'Milestone Reward',
                'verbose_name_plural': 'Milestone Rewards',
                'ordering': ['tasks_required'],
            },
        ),
    ]
