# Generated by Django 4.2.16 on 2024-12-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_milestonereward'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralMilestoneReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks_required', models.PositiveIntegerField(help_text='Number of tasks a referred user must complete to trigger this reward.')),
                ('points', models.PositiveIntegerField(help_text='Points to award to the referring user upon milestone completion.')),
            ],
            options={
                'verbose_name': 'Referral Milestone Reward',
                'verbose_name_plural': 'Referral Milestone Rewards',
                'ordering': ['tasks_required'],
            },
        ),
        migrations.DeleteModel(
            name='MilestoneReward',
        ),
    ]
