# Generated by Django 4.2.16 on 2024-12-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_referralmilestonereward_delete_milestonereward'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Image Name')),
                ('image', models.ImageField(upload_to='task_images/', verbose_name='Predefined Task Image')),
            ],
        ),
    ]
