# Generated by Django 4.2.16 on 2024-12-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_taskimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskImage',
            new_name='PredefinedImage',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_image',
        ),
        migrations.AddField(
            model_name='task',
            name='predefined_image',
            field=models.CharField(blank=True, choices=[('YouTube', 'YouTube'), ('Instagram', 'Instagram'), ('Google', 'Google')], max_length=50, null=True, verbose_name='Predefined Image'),
        ),
    ]
