# Generated by Django 4.2.16 on 2024-12-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_rename_taskimage_predefinedimage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferralLink',
        ),
    ]
