# Generated by Django 4.2.16 on 2024-12-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_delete_referrallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinConversionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField(default=1)),
                ('rupees', models.FloatField(default=1.0)),
            ],
        ),
        migrations.DeleteModel(
            name='ReferralTracking',
        ),
    ]
