# Generated by Django 4.2.16 on 2024-12-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_coinconversionrate_delete_referraltracking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredefinedImage',
        ),
    ]
